<Project Sdk="Uno.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Pretext\Pretext.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net10.0-desktop</TargetFrameworks>
    <UnoSingleProject>true</UnoSingleProject>
    <OutputType>Library</OutputType>
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <UnoFeatures>
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>
</Project>
